Meg branch local
zbialik/clue-less pull request #72
Opened 2021-04-10 20:26 UTC by mgtucks

Updated Has Clue

2021-04-10 20:27 UTC, mgtucks commented
**whoHasClue not hasClue

2021-04-11 12:41 UTC, zbialik commented on src/main/java/clueless/Game.java
> +		Player pl = null;
rather that initializing and assigning to null and returning `pl` at the end, just initialize it here and if you make it to the end of method return null

2021-04-11 12:41 UTC, zbialik commented on src/main/java/clueless/Game.java
> +			return pl;
```suggestion
			return null;
```

2021-04-11 12:42 UTC, zbialik commented on src/main/java/clueless/Game.java
> +			while ((!playerHasClue) && i < this.characterMap.size())
you reference i here but never increment `i`, did you mean to use `count` here? If so, you should initialize count outside this while loop

2021-04-11 13:03 UTC, zbialik commented on src/main/java/clueless/Game.java
> +						pl = this.getPlayer(CHARACTER_TURN_ORDER[nextPlayerindex]);
```suggestion
						return this.getPlayer(CHARACTER_TURN_ORDER[nextPlayerindex]);
```

you can just return the player that has a clue here

2021-04-11 13:06 UTC, zbialik requested changes
looks good -- just need remediate the counter in that while loop comment

2021-04-11 13:44 UTC, closed without merging